// Heraldic data: devices, colours, shapes, and display names

const deviceList = [
  "img/devices/axe.png",
  "img/devices/balance.png",
  "img/devices/basilisk-sejant.png",
  "img/devices/battle-axe.png",
  "img/devices/boar.png",
  "img/devices/boar-rampant.png",
  "img/devices/boars-head-erased.png",
  "img/devices/bulls-head-cabossed.png",
  "img/devices/castle-1.png",
  "img/devices/castle-2.png",
  "img/devices/castle-3.png",
  "img/devices/castle-of-three-towers.png",
  "img/devices/cormorants-head-erased.png",
  "img/devices/cross-formy.png",
  "img/devices/cross-formy-fitchy-1.png",
  "img/devices/cross-formy-fitchy-2.png",
  "img/devices/crown.png",
  "img/devices/crown-flory.png",
  "img/devices/cup.png",
  "img/devices/dragon-rampant.png",
  "img/devices/dragon-rampant-inflamed.png",
  "img/devices/dragon-rampant-regardant.png",
  "img/devices/dragon-statant.png",
  "img/devices/eagle.png",
  "img/devices/estoile.png",
  "img/devices/fleur-de-lys-1.png",
  "img/devices/fleur-de-lys-2.png",
  "img/devices/fleur-de-lys-3.png",
  "img/devices/fleur-de-lys-4.png",
  "img/devices/fleur-de-lys-trident-1.png",
  "img/devices/fleur-de-lys-trident-2.png",
  "img/devices/goutte.png",
  "img/devices/green-man.png",
  "img/devices/griffins-leg-erased.png",
  "img/devices/griffins-leg-with-hand-erased.png",
  "img/devices/key.png",
  "img/devices/lion.png",
  "img/devices/lion-passant.png",
  "img/devices/lion-passant-guardant.png",
  "img/devices/lion-queue-nowed.png",
  "img/devices/lion-regardant.png",
  "img/devices/lions-head-cabossed.png",
  "img/devices/lions-head-jessant-de-lys.png",
  "img/devices/mace-spiked.png",
  "img/devices/mourning-drape.png",
  "img/devices/pegasus-courant.png",
  "img/devices/pegasus-segreant-1.png",
  "img/devices/pegasus-segreant-2.png",
  "img/devices/pegasus-segreant-displayed.png",
  "img/devices/pegasus-segreant-regardant.png",
  "img/devices/raven.png",
  "img/devices/rose-slipped-and-leaved.png",
  "img/devices/sea-lion-embowed.png",
  "img/devices/sea-lion-ii.png",
  "img/devices/sea-lion-iii.png",
  "img/devices/sea-lion-iv.png",
  "img/devices/serpent-erect.png",
  "img/devices/skull.png",
  "img/devices/stag-head.png",
  "img/devices/stag-rampant.png",
  "img/devices/stag-rampant-regardant.png",
  "img/devices/stags-head-couped.png",
  "img/devices/stag-trippant.png",
  "img/devices/sun.png",
  "img/devices/sun-2.png",
  "img/devices/sun-rays.png",
  "img/devices/sword.png",
  "img/devices/sword-2.png",
  "img/devices/toad.png",
  "img/devices/tower.png",
  "img/devices/trident.png",
  "img/devices/trident-2.png",
  "img/devices/unicorn.png",
  "img/devices/unicorn-passant.png",
  "img/devices/unicorn-passant-regardant.png",
  "img/devices/unicorn-rampant-regardant.png",
  "img/devices/wings-conjoined-in-lure.png",
  "img/devices/wyvern-erect-inflamed.png",
];

var colours = {
  0: "#d4af34", // or
  1: "#ffffff", // argent
  2: "#3953a4", // azure
  3: "#790000", // gules
  4: "#000000", // sable
  5: "#11671d", // vert
  6: "#dbdbdb", // cendree
  7: "#7b3f8c", // purpure
};

var shapes = {
  0: "barry",
  1: "base",
  2: "bend",
  3: "bendSinister",
  4: "bendy",
  5: "bordure",
  6: "canton",
  7: "chequy",
  8: "chevron",
  9: "chevronny",
  10: "chief",
  11: "cross",
  12: "fess",
  13: "flaunches",
  14: "fret",
  15: "gyronny6",
  16: "gyronny",
  17: "gyronny12",
  18: "label",
  19: "lozengy",
  20: "orle",
  21: "pale",
  22: "pall",
  23: "pally",
  24: "partyPerBendSinister",
  25: "partyPerFess",
  26: "partyPerPale",
  27: "pile",
  28: "quarter",
  29: "quarterly",
  30: "saltire",
  31: "tressure",
};

const colourNames = {
  "#d4af34": "Or",
  "#ffffff": "Argent",
  "#3953a4": "Azure",
  "#790000": "Gules",
  "#000000": "Sable",
  "#11671d": "Vert",
  "#dbdbdb": "Cendré",
  "#7b3f8c": "Purpure",
};

const shapeNames = {
  barry: "Barry",
  base: "Base",
  bend: "Bend",
  bendSinister: "Bend Sinister",
  bendy: "Bendy",
  bordure: "Bordure",
  canton: "Canton",
  chequy: "Chequy",
  chevron: "Chevron",
  chevronny: "Chevronny",
  chief: "Chief",
  cross: "Cross",
  fess: "Fess",
  flaunches: "Flaunches",
  fret: "Fret",
  gyronny6: "Gyronny of 6",
  gyronny: "Gyronny of 8",
  gyronny12: "Gyronny of 12",
  label: "Label",
  lozengy: "Lozengy",
  orle: "Orle",
  pale: "Pale",
  pall: "Pall",
  pally: "Pally",
  partyPerBendSinister: "Party per Bend Sinister",
  partyPerFess: "Party per Fess",
  partyPerPale: "Party per Pale",
  pile: "Pile",
  quarter: "Quarter",
  quarterly: "Quarterly",
  saltire: "Saltire",
  tressure: "Tressure",
};

const geometricCharges = [
  "annulet",
  "billet",
  "cross-botonny",
  "cross-crosslet",
  "cross-flory",
  "cross-maltese",
  "cross-moline",
  "cross-patonce",
  "cross-pattee",
  "cross-potent",
  "escutcheon",
  "fountain",
  "fusil",
  "lozenge",
  "mascle",
  "roundel",
  "rustre",
];

const geometricDisplayNames = {
  annulet: "Annulet",
  billet: "Billet",
  "cross-botonny": "Cross Botonny",
  "cross-crosslet": "Cross Crosslet",
  "cross-flory": "Cross Flory",
  "cross-maltese": "Maltese Cross",
  "cross-moline": "Cross Moline",
  "cross-patonce": "Cross Patonce",
  "cross-pattee": "Cross Pattée",
  "cross-potent": "Cross Potent",
  escutcheon: "Escutcheon",
  fountain: "Fountain",
  fusil: "Fusil",
  lozenge: "Lozenge",
  mascle: "Mascle",
  rustre: "Rustre",
  roundel: "Roundel",
};

// Bretonnian rules data
const bretonnianExcluded = ["#11671d", "#7b3f8c"]; // vert, purpure

const bretonnianFavouredDevices = [
  "img/devices/fleur-de-lys-1.png",
  "img/devices/fleur-de-lys-2.png",
  "img/devices/fleur-de-lys-3.png",
  "img/devices/fleur-de-lys-4.png",
  "img/devices/fleur-de-lys-trident-1.png",
  "img/devices/fleur-de-lys-trident-2.png",
  "img/devices/cup.png",
];

// Rule of tincture: metals (Or, Argent, Cendré) go on colours and vice-versa.
const metals = new Set(["#d4af34", "#ffffff", "#dbdbdb"]);
